name: Monthly CSV Aggregation

on:
  schedule:
    - cron: '0 0 1 * *'  # Uruchamiany 1-go dnia miesiąca o 00:00 UTC
  workflow_dispatch:

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gałęzi data-archive
        uses: actions/checkout@v4
        with:
          ref: data-archive

      - name: Ustawienie środowiska Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalacja zależności
        run: pip install pandas

      - name: Uruchomienie skryptu agregującego
        run: python aggregate.py

      - name: Upload zbiorczego pliku jako artefakt
        uses: actions/upload-artifact@v4
        with:
          name: aggregated-csv
          path: aggregated_*.csv
