name: Monthly CSV Aggregation

on:
  schedule:
    - cron: '0 0 1 * *'  # Uruchamiany 1-go dnia miesiąca o 00:00 UTC
  workflow_dispatch:

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz repozytorium
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pobiera całe repozytorium

      - name: Pobierz branch `data-archive`
        run: |
          git fetch origin
          git checkout origin/data-archive

      - name: Sprawdzenie zawartości katalogu
        run: ls -R

      - name: Zainstaluj pandas
        run: pip install pandas

      - name: Uruchom agregację danych
        run: python aggregate.py
